routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes(['verify' => true]);

Route::group([
    'middleware' => ['auth', 'verified']
], function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('/upload', [App\Http\Controllers\FileController::class, 'upload']);
    Route::post('/update/{work}', [App\Http\Controllers\FileController::class, 'update']);
    Route::get('/download/{work}/{type?}', [App\Http\Controllers\FileController::class, 'download']);
});

Route::group([
    'prefix' => 'admin',
    'middleware' => ['admin'],
    'as' => 'admin.'
], function(){
    Route::view('/', 'admin.index')->name('index');
    Route::resource('/users', App\Http\Controllers\UserController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    protected $fillable = [
        'name',
        'email',
        'password',
        'active',
        'admin'
    ];
    protected $hidden = [
        'password',
        'remember_token',
    ];
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    protected $with = ['filters', 'works'];
    public function isAdmin(){
        return $this->admin;
    }
    public function works(){
        return $this->hasMany(Work::class);
    }
    public function filters(){
        return $this->belongsToMany(Filter::class)->withPivot('quantity');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\FilterCategory;
use App\Models\Filter;
class UserController extends Controller
{
    public function index()
    {
        $users = User::paginate(25);
        return view('admin.users.index', compact('users'));
    }

    public function create()
    {
        //
    }
    public function store(Request $request)
    {
        //
    }
    
    public function edit(User $user)
    {
        $filters = Filter::all();
        $userFilters = [];
        foreach($user->filters as $f){
            $userFilters[$f->id] = $f->pivot->quantity;
        }
        return view('admin.users.edit', compact('user', 'filters', 'userFilters'));
    }

    public function update(Request $request, User $user)
    {
        $syncData = [];
        foreach($request->q as $key => $val){
            $syncData[$key] = [
                'quantity' => $val
            ];
        }
        $user->filters()->sync( $syncData );
        if($request->active) $user->active = 1;
        if($request->admin) $user->admin = 1;
        $user->save();
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-9"><h5>Редактирование пользователя <b>{{$user->email}}</b></h5></div>
    <div class="col-md-3 text-right">
        <form action="{{route('admin.users.destroy', $user->id)}}" method="post" class="confirmed d-inline">
            @csrf
            <input type="hidden" name="_method" value="DELETE">
            <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Удалить</button>
        </form>
    </div>
</div>
<hr>
<form action="{{route('admin.users.update', $user->id)}}" method="POST">
    @csrf
    <input type="hidden" name="_method" value="PUT">
    <div class="row">
        @foreach($filters as $f)
            <div class="col">
                <label>{{$f->name}}</label>
                <input type="text" class="form-control" name="q[{{$f->id}}]" value="{{$userFilters[$f->id] ?? 0}}">
            </div>
        @endforeach
    </div>
    <hr>
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="active" @if($user->active) checked @endif @if($user->id == 1) disabled @endif>
        <label class="form-check-label" for="active">Активность</label>
    </div>
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="admin" @if($user->admin) checked @endif @if($user->id == 1) disabled @endif>
        <label class="form-check-label" for="admin">Сделать администратором</label>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <input name="name" disabled value="{{old('name') ? old('name') : $user->name}}" type="text" class="form-control">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <input name="email" disabled value="{{old('email') ? old('email') : $user->email}}" type="text" class="form-control">
            </div>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary btn-sm" type="submit">Сохранить</button>
    </div>
</form>
<hr>
<h4>Фото пользователя</h4>
@if($user->works->count())
<works :works="{{$user->works}}"></works>
@else
    Не найдено
@endif
@stop

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')
<h2>Список пользователей</h2>
<div class="table-responsive">
    <table class="table table-striped table-sm">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>E-mail</th>
            <th>Photos</th>
            <th>Actions</th>
        </tr>
        @foreach($users as $user)
        <tr>
            <td>{{$user->id}}</td>
            <td>{{$user->name}}</td>
            <td>{{$user->email}}</td>
            <td>0</td>
            <td>
                <a href="{{route('admin.users.edit', $user->id)}}" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i></a>
            </td>
        </tr>
        @endforeach
    </table>
</div>
@stop